/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ifpb.com.br;

import javax.swing.JOptionPane;

/**
 *
 * @author GustavoRamos
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jD_Modelos = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jM_Arquivo = new javax.swing.JMenu();
        jM_Sair = new javax.swing.JMenuItem();
        jM_Modelos = new javax.swing.JMenu();
        jM_Difração = new javax.swing.JMenuItem();
        jM_DoisRaios = new javax.swing.JMenuItem();
        jM_EspaçoLivre = new javax.swing.JMenuItem();
        jM_Simplificado = new javax.swing.JMenuItem();
        jM_Sobre = new javax.swing.JMenu();
        jM_Ajuda = new javax.swing.JMenuItem();
        jM_Desenvolvedores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jD_ModelosLayout = new javax.swing.GroupLayout(jD_Modelos);
        jD_Modelos.setLayout(jD_ModelosLayout);
        jD_ModelosLayout.setHorizontalGroup(
            jD_ModelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );
        jD_ModelosLayout.setVerticalGroup(
            jD_ModelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );

        jM_Arquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons 1/house.png"))); // NOI18N
        jM_Arquivo.setText("Arquivo");

        jM_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons 1/shape_square_go.png"))); // NOI18N
        jM_Sair.setText("Sair");
        jM_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_SairActionPerformed(evt);
            }
        });
        jM_Arquivo.add(jM_Sair);

        jMenuBar1.add(jM_Arquivo);

        jM_Modelos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons 1/transmit.png"))); // NOI18N
        jM_Modelos.setText("Modelos");

        jM_Difração.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons 1/transmit_blue.png"))); // NOI18N
        jM_Difração.setText("Difração");
        jM_Difração.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_DifraçãoActionPerformed(evt);
            }
        });
        jM_Modelos.add(jM_Difração);

        jM_DoisRaios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons 1/transmit_blue.png"))); // NOI18N
        jM_DoisRaios.setText("Dois Raios");
        jM_DoisRaios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_DoisRaiosActionPerformed(evt);
            }
        });
        jM_Modelos.add(jM_DoisRaios);

        jM_EspaçoLivre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons 1/transmit_blue.png"))); // NOI18N
        jM_EspaçoLivre.setText("Espaço Livre");
        jM_EspaçoLivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_EspaçoLivreActionPerformed(evt);
            }
        });
        jM_Modelos.add(jM_EspaçoLivre);

        jM_Simplificado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons 1/transmit_blue.png"))); // NOI18N
        jM_Simplificado.setText("Simplificado");
        jM_Simplificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_SimplificadoActionPerformed(evt);
            }
        });
        jM_Modelos.add(jM_Simplificado);

        jMenuBar1.add(jM_Modelos);

        jM_Sobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons 1/information.png"))); // NOI18N
        jM_Sobre.setText("Sobre");

        jM_Ajuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons 1/help.png"))); // NOI18N
        jM_Ajuda.setText("Ajuda");
        jM_Sobre.add(jM_Ajuda);

        jM_Desenvolvedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons 1/group_gear.png"))); // NOI18N
        jM_Desenvolvedores.setText("Desenvolvedores");
        jM_Desenvolvedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_DesenvolvedoresActionPerformed(evt);
            }
        });
        jM_Sobre.add(jM_Desenvolvedores);

        jMenuBar1.add(jM_Sobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jD_Modelos)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jD_Modelos, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        setSize(new java.awt.Dimension(620, 372));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jM_DifraçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_DifraçãoActionPerformed
        Difração obj= new Difração();
        jD_Modelos.add(obj);
        obj.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jM_DifraçãoActionPerformed

    private void jM_DesenvolvedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_DesenvolvedoresActionPerformed
        JOptionPane.showMessageDialog(this, "Gustavo Ramos \nRychelly Glennesson\nVersion 1.0");// TODO add your handling code here:
    }//GEN-LAST:event_jM_DesenvolvedoresActionPerformed

    private void jM_SimplificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_SimplificadoActionPerformed
        Simplificado obj= new Simplificado();
        jD_Modelos.add(obj);
        obj.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jM_SimplificadoActionPerformed

    private void jM_DoisRaiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_DoisRaiosActionPerformed
        DoisRaios obj=new DoisRaios();
        jD_Modelos.add(obj);
        obj.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jM_DoisRaiosActionPerformed

    private void jM_EspaçoLivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_EspaçoLivreActionPerformed
       EspaçoLivre obj= new EspaçoLivre();
       jD_Modelos.add(obj);
       obj.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jM_EspaçoLivreActionPerformed

    private void jM_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_SairActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_jM_SairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jD_Modelos;
    private javax.swing.JMenuItem jM_Ajuda;
    private javax.swing.JMenu jM_Arquivo;
    private javax.swing.JMenuItem jM_Desenvolvedores;
    private javax.swing.JMenuItem jM_Difração;
    private javax.swing.JMenuItem jM_DoisRaios;
    private javax.swing.JMenuItem jM_EspaçoLivre;
    private javax.swing.JMenu jM_Modelos;
    private javax.swing.JMenuItem jM_Sair;
    private javax.swing.JMenuItem jM_Simplificado;
    private javax.swing.JMenu jM_Sobre;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
